version: '3.8'

services:
    api:
        container_name: api-container
        image: apac_api_img
        command: /bin/bash -c "cd code && npm i && npm start"
        secrets:
            - MONGO_CLUSTER
            - MONGO_DB_NAME
            - MONGO_USER
            - MONGO_PASSWORD
            - AUTH_KEY
            - SERVICE
            - EMAIL
            - EMAIL_PORT
            - SECURE
            - USER_EMAIL
            - USER_PASS
            - PAYPAL_CLIENT_ID
            - PAYPAL_CLIENT_SECRET
            - PAYPAL_ENVIRONMENT
            - PAYPAL_SANDBOX_URL
            - PAYPAL_LIVE_URL
            - EUPAGO_CLIENT_ID
            - EUPAGO_CLIENT_SECRET
            - EUPAGO_API_KEY
            - EUPAGO_USERNAME
            - EUPAGO_PASSWORD
            - EUPAGO_ENVIRONMENT
            - EUPAGO_SANDBOX_URL
            - EUPAGO_LIVE_URL
        ports:
            - 11000:80
        networks:
            - apac-network

    auth:
        container_name: auth-container
        image: apac_auth_img
        command: /bin/bash -c "cd code && npm i && npm start"
        secrets:
            - MONGO_CLUSTER
            - MONGO_DB_NAME
            - MONGO_USER
            - MONGO_PASSWORD
            - AUTH_KEY
        ports:
            - 11001:80
        networks:
            - apac-network

#  chat:
#    container_name: chat-container
#    image: apac_chat_img
#    command: /bin/bash -c "cd code && npm i && npm start"
#    secrets:
#      - MONGO_CLUSTER
#      - MONGO_DB_NAME
#      - MONGO_USER
#      - MONGO_PASSWORD
#    ports:
#      - 11002:80
#    networks:
#      - apac-network

volumes:
    dbdata:

secrets:
    MONGO_CLUSTER:
        file: ./env/MONGO_CLUSTER.txt
    MONGO_DB_NAME:
        file: ./env/MONGO_DB_NAME.txt
    MONGO_USER:
        file: ./env/MONGO_USER.txt
    MONGO_PASSWORD:
        file: ./env/MONGO_PASSWORD.txt
    AUTH_KEY:
        file: ./env/AUTH_KEY.txt
    PAYPAL_CLIENT_ID:
        file: ./env/PAYPAL_CLIENT_ID.txt
    PAYPAL_CLIENT_SECRET:
        file: ./env/PAYPAL_CLIENT_SECRET.txt
    PAYPAL_ENVIRONMENT:
        file: ./env/PAYPAL_ENVIRONMENT.txt
    PAYPAL_SANDBOX_URL:
        file: ./env/PAYPAL_SANDBOX_URL.txt
    PAYPAL_LIVE_URL:
        file: ./env/PAYPAL_LIVE_URL.txt
    EUPAGO_CLIENT_ID:
        file: ./env/EUPAGO_CLIENT_ID.txt
    EUPAGO_CLIENT_SECRET:
        file: ./env/EUPAGO_CLIENT_SECRET.txt
    EUPAGO_API_KEY:
        file: ./env/EUPAGO_API_KEY.txt
    EUPAGO_USERNAME:
        file: ./env/EUPAGO_USERNAME.txt
    EUPAGO_PASSWORD:
        file: ./env/EUPAGO_PASSWORD.txt
    EUPAGO_ENVIRONMENT:
        file: ./env/EUPAGO_ENVIRONMENT.txt
    EUPAGO_SANDBOX_URL:
        file: ./env/EUPAGO_SANDBOX_URL.txt
    EUPAGO_LIVE_URL:
        file: ./env/EUPAGO_LIVE_URL.txt
    EMAIL:
        file: ./env/EMAIL.txt
    SERVICE:
        file: ./env/SERVICE.txt
    EMAIL_PORT:
        file: ./env/EMAIL_PORT.txt
    SECURE:
        file: ./env/SECURE.txt
    USER_EMAIL:
        file: ./env/USER_EMAIL.txt
    USER_PASS:
        file: ./env/USER_PASS.txt

networks:
    # tcp-ip
    apac-network:
        driver: bridge