version: '3.8'

services:
  api:
    container_name: api-container
    image: apac_api_img
    command: /bin/bash -c "cd code && npm i && npm start"
    secrets:
      - MONGO_CLUSTER
      - MONGO_DB_NAME
      - MONGO_USER
      - MONGO_PASSWORD
    ports:
      - 11000:80
    networks:
      - apac-network

  auth:
    container_name: auth-container
    image: apac_auth_img
    command: /bin/bash -c "cd code && npm i && npm start"
    secrets:
      - MONGO_CLUSTER
      - MONGO_DB_NAME
      - MONGO_USER
      - MONGO_PASSWORD
      - AUTH_KEY
    
    networks:
      - apac-network

volumes:
  dbdata:

secrets:
  MONGO_CLUSTER:
    file: ./env/MONGO_CLUSTER.txt
  MONGO_DB_NAME:
    file: ./env/MONGO_DB_NAME.txt
  MONGO_USER:
    file: ./env/MONGO_USER.txt
  MONGO_PASSWORD:
    file: ./env/MONGO_PASSWORD.txt
  AUTH_KEY:
    file: ./env/AUTH_KEY.txt


networks:
  # tcp-ip
  apac-network:
    driver: bridge