version: '1'

services:
  api:
    container_name: api
    build: ./api
#    restart: always
    depends_on:
      - auth
    env_file:
      - .env
    ports:
      - 11000:80
    networks:
      - apac-network

  auth:
    container_name: auth
    build: ./auth
#    restart: always
    env_file:
      - .env
    networks:
      - apac-network

volumes:
  dbdata:

networks:
  # tcp-ip
  apac-network:
    driver: bridge
